### ISSUE TITLE
Research Business Logic Handling

### ISSUE THREAD

**Issue by nguyendhst** [nguyendhst/HK231-Specialized-Project#7]
- Research business logic/workflow of other platforms, ERP, etc.

**Comment by FukutoTojido** [comment]
Lack of insight in each field of usage. Need to rely on user's input rather than providing them with an existing set of Business Processes.

**Comment by nguyendhst** [comment]
Reference suggestion: https://docs.mendix.com/refguide/activities/

**Comment by FukutoTojido** [comment]
App Navigation is clearly not a Business Logics
Considering removing that

**Comment by FukutoTojido** [comment]
Yet there needs to be a separation between Business Logic and Application Logic since we are mixing these terms up

**Comment by nguyendhst** [comment]
> Yet there needs to be a separation between Business Logic and Application Logic since we are mixing these terms up

Consider input it into the research notes

**Comment by nguyendhst** [comment]
A few notes based on the previous meeting:
- Consider input into this section of the report: https://github.com/nguyendhst/HK231-Specialized-Project/blob/main/documentation/report/literature-review.md
- Best practice: UI component for general and specific Business Domains, Template Workflows (sampling process of ERP systems, etc.)
- Case study: Comparison of low-code platform on the market (enterprise, OS, etc.)

**Comment by FukutoTojido** [comment]
- [ ] Provide details about 3 different categories of Low-code Platforms
- [ ] Compare these Platforms using a table format
- [ ] Decide which parts are going to be implemented
