### ISSUE TITLE
Build Usecases

### ISSUE THREAD

**Issue by nguyendhst** [nguyendhst/HK231-Specialized-Project#9]
- Usecase/user scenario etc.

**Comment by FukutoTojido** [comment]
### Users
- Remove "Invite new user"
### Data
- Rework usecase "Connect to external Data Source" to fit with system design

**Comment by NgTrNghia1211** [comment]
# Functional Requirement
- Detail each general requirement
# Nonfunctional Requirement
- Estimate load of each requirement
- Must testable
# Usecase
- Add usecase diagram for each general usecase

**Comment by nguyendhst** [comment]
A few extra notes from the previous meeting:
- Consider input into this section of the report: https://github.com/nguyendhst/HK231-Specialized-Project/blob/main/documentation/report/requirement-analysis.md
- Clearer and more specific functional and non-functional reqs.
- Avoid non-functional reqs that might be not testable

**Comment by FukutoTojido** [comment]
# Actors
- [ ] Remove End-users
- [ ] Third Provider -> Third-party Provider

# Requirements
- [ ] Split Sign Up and Sign In into 2 different use-cases
- [ ] Split Edit/Update Project and DnD Application Builder Interface into 2 different use-cases
- [ ] Merge search and filter projects into one use-case
- [ ] Merge connecting to external data sources to creating data models as a whole
- [ ] Consider moving staging support to optional (or remove completely)
- [ ] Push business process to the top
- [ ] Consider adding Localization to Non Functional Requirements
